import type { CardMeta, DuoPairing, MetaDeck } from "./types";

/** Snapshot compiled from September 2026 ladder reports (RoyaleAPI / tracker week of Sep 8). */
export const META_AS_OF = "2026-09-08";
export const META_LABEL = "Season 87 · Minion Academy";

export const META_DECKS: MetaDeck[] = [
  {
    id: "hog-cycle",
    name: "Hog Cycle",
    archetype: "cycle",
    modes: ["ladder", "war", "2v2"],
    cards: ["hog-rider", "musketeer", "ice-golem", "cannon", "skeletons", "ice-spirit", "the-log", "fireball"],
    evo: ["skeletons", "cannon"],
    elixir: 2.6,
    winRate: 54.2,
    useRate: 11.4,
    sample: 48200,
    notes: "Best all-round ladder deck after the Spirit nerf. Cheap, forgiving, and it never needed tower chip from Spirits.",
    f2p: true,
  },
  {
    id: "log-bait",
    name: "Goblin Barrel Bait",
    archetype: "bait",
    modes: ["ladder", "2v2"],
    cards: ["goblin-barrel", "princess", "goblin-gang", "inferno-tower", "knight", "ice-spirit", "the-log", "rocket"],
    evo: ["goblin-barrel", "knight"],
    elixir: 3.3,
    winRate: 53.1,
    useRate: 12.8,
    sample: 51100,
    notes: "Highest use-rate archetype through mid-ladder. Punishes spent small spells; Princess Evo is a luxury, not required.",
    f2p: false,
  },
  {
    id: "hog-miner",
    name: "Hog Mighty Miner",
    archetype: "cycle",
    modes: ["ladder"],
    cards: ["hog-rider", "mighty-miner", "firecracker", "skeletons", "archers", "the-log", "earthquake", "royal-delivery"],
    evo: ["firecracker", "archers"],
    champion: "mighty-miner",
    elixir: 2.9,
    winRate: 54.0,
    useRate: 2.4,
    sample: 8750,
    notes: "Top-10 ranked list staple. Earthquake plus Delivery covers buildings and bait in one package.",
    f2p: false,
  },
  {
    id: "hogs-queen",
    name: "Royal Hogs Queen",
    archetype: "cycle",
    modes: ["ladder", "war"],
    cards: ["royal-hogs", "archer-queen", "cannon", "skeletons", "ice-spirit", "the-log", "earthquake", "royal-delivery"],
    evo: ["royal-hogs", "cannon"],
    champion: "archer-queen",
    elixir: 2.9,
    winRate: 55.9,
    useRate: 1.5,
    sample: 6200,
    notes: "Highest win rate among Hogs variants this week. Evo Hogs plus Queen ability still close games after Spirits lost chip.",
    f2p: false,
  },
  {
    id: "hogs-stein",
    name: "Royal Hogs Goblinstein",
    archetype: "midrange",
    modes: ["ladder", "2v2"],
    cards: ["royal-hogs", "goblinstein", "archers", "skeletons", "ice-spirit", "the-log", "earthquake", "royal-delivery"],
    evo: ["royal-hogs", "archers"],
    champion: "goblinstein",
    elixir: 2.9,
    winRate: 53.6,
    useRate: 1.7,
    sample: 5400,
    notes: "Stein monster tanks for Hogs; Doctor ability is single-use so save it for the second push.",
    f2p: false,
  },
  {
    id: "ram-pekka",
    name: "Ram PEKKA Magic Archer",
    archetype: "bridge",
    modes: ["ladder", "2v2"],
    cards: ["battle-ram", "pekka", "magic-archer", "royal-ghost", "electro-wizard", "bandit", "fireball", "zap"],
    evo: ["battle-ram"],
    hero: "magic-archer-hero",
    elixir: 3.9,
    winRate: 55.3,
    useRate: 0.8,
    sample: 3100,
    notes: "Low-use, high-win bridge spam. Hero Magic Archer is the skill card — the rest is standard PEKKA control.",
    f2p: false,
  },
  {
    id: "loon-control",
    name: "Lumberloon Bowler",
    archetype: "control",
    modes: ["ladder", "2v2"],
    cards: ["balloon", "inferno-dragon", "baby-dragon", "bowler", "knight", "freeze", "tornado", "barbarian-barrel"],
    evo: ["baby-dragon", "inferno-dragon"],
    hero: "knight-hero",
    elixir: 3.8,
    winRate: 52.8,
    useRate: 2.4,
    sample: 9100,
    notes: "Classic freeze loon with extra air control. Hero Knight soaks the kiting value Balloon always wanted.",
    f2p: false,
  },
  {
    id: "ram-witch",
    name: "Ram Ghost Mother Witch",
    archetype: "bridge",
    modes: ["ladder"],
    cards: ["battle-ram", "wizard", "royal-ghost", "giant-skeleton", "zappies", "mother-witch", "barbarian-barrel", "vines"],
    evo: ["battle-ram", "royal-ghost"],
    hero: "wizard-hero",
    elixir: 3.9,
    winRate: 52.7,
    useRate: 2.5,
    sample: 8800,
    notes: "Vines replaced Zap in this line after the August patch. Giant Skeleton death bomb still wins messy bridges.",
    f2p: false,
  },
  {
    id: "miner-poison",
    name: "Miner Poison",
    archetype: "control",
    modes: ["ladder", "war"],
    cards: ["miner", "poison", "bats", "skeletons", "valkyrie", "musketeer", "cannon", "the-log"],
    evo: ["bats", "valkyrie"],
    elixir: 2.9,
    winRate: 53.8,
    useRate: 4.1,
    sample: 15200,
    notes: "Control is the biggest winner of the slowed meta. Chip behind a solid defense; Poison is the closer.",
    f2p: false,
  },
  {
    id: "xbow",
    name: "X-Bow 3.0",
    archetype: "siege",
    modes: ["ladder"],
    cards: ["x-bow", "tesla", "archers", "knight", "skeletons", "ice-spirit", "the-log", "fireball"],
    evo: ["tesla", "archers"],
    elixir: 3.0,
    winRate: 52.1,
    useRate: 2.2,
    sample: 7400,
    notes: "Siege is back after the X-Bow hit-speed bugfix. High skill, punishing if Tesla Evo is missing.",
    f2p: true,
  },
  {
    id: "golem",
    name: "Golem Night Witch",
    archetype: "beatdown",
    modes: ["ladder", "2v2", "war"],
    cards: ["golem", "night-witch", "baby-dragon", "mega-minion", "lumberjack", "lightning", "tornado", "barbarian-barrel"],
    evo: ["baby-dragon", "lumberjack"],
    elixir: 4.3,
    winRate: 52.4,
    useRate: 1.8,
    sample: 6100,
    notes: "Ignores the Spirit nerf entirely. Wins in double elixir. Weak first minute — pair it in 2v2 with a cycle partner.",
    f2p: false,
  },
  {
    id: "egiant",
    name: "Electro Giant Control",
    archetype: "beatdown",
    modes: ["ladder", "2v2"],
    cards: ["electro-giant", "tornado", "lightning", "tesla", "dark-prince", "electro-dragon", "barbarian-barrel", "bats"],
    evo: ["tesla", "electro-dragon"],
    elixir: 4.1,
    winRate: 51.9,
    useRate: 1.4,
    sample: 4300,
    notes: "EG damage is up this patch. Tornado value is the whole deck — skip it if you do not already play the pull.",
    f2p: false,
  },
  {
    id: "mk-bait",
    name: "Mega Knight Bait",
    archetype: "bait",
    modes: ["ladder", "2v2"],
    cards: ["mega-knight", "goblin-barrel", "goblin-gang", "spear-goblins", "bats", "inferno-dragon", "fireball", "zap"],
    evo: ["mega-knight", "bats"],
    elixir: 3.4,
    winRate: 53.7,
    useRate: 7.2,
    sample: 26800,
    notes: "Mid-ladder king. MK Evo is optional; the bait package is what actually wins trophies.",
    f2p: false,
  },
  {
    id: "mortar-bait",
    name: "Mortar Barrel Goblins",
    archetype: "siege",
    modes: ["ladder", "2v2"],
    cards: ["mortar", "skeleton-barrel", "goblins", "minions", "rascals", "cannon-cart", "fireball", "barbarian-barrel"],
    evo: ["mortar", "skeleton-barrel"],
    hero: "goblins-hero",
    elixir: 3.5,
    winRate: 54.8,
    useRate: 0.2,
    sample: 980,
    notes: "Sleeper of the week. Tiny sample, huge win rate — Hero Goblins plus Mortar Evo is a nasty chip engine.",
    f2p: true,
  },
  {
    id: "loon-miner",
    name: "Balloon Miner Cycle",
    archetype: "cycle",
    modes: ["ladder"],
    cards: ["balloon", "miner", "musketeer", "skeletons", "ice-spirit", "the-log", "earthquake", "royal-delivery"],
    evo: ["musketeer"],
    hero: "balloon-hero",
    elixir: 2.8,
    winRate: 51.5,
    useRate: 2.0,
    sample: 6700,
    notes: "Hero Balloon is the new finisher. Earthquake keeps buildings honest so Miner can walk in.",
    f2p: false,
  },
  {
    id: "hog-f2p",
    name: "Budget Hog",
    archetype: "cycle",
    modes: ["ladder", "war"],
    cards: ["hog-rider", "musketeer", "valkyrie", "cannon", "skeletons", "ice-spirit", "arrows", "fireball"],
    evo: ["skeletons", "valkyrie"],
    elixir: 3.0,
    winRate: 53.0,
    useRate: 3.6,
    sample: 12100,
    notes: "No legendaries, no champions. The right climb deck if gold is the bottleneck.",
    f2p: true,
  },
];

export const DUOS: DuoPairing[] = [
  {
    id: "cycle-beatdown",
    name: "Hog + Golem",
    deckA: "hog-cycle",
    deckB: "golem",
    winRate: 56.1,
    notes: "The textbook 2v2 pair: cheap pressure while the beatdown partner banks for a double-elixir push.",
  },
  {
    id: "bait-hogs",
    name: "Bait + Royal Hogs",
    deckA: "log-bait",
    deckB: "hogs-queen",
    winRate: 55.4,
    notes: "Spell bait forces the Log; Hogs walk in the other lane. Cover air between Princess and Queen.",
  },
  {
    id: "loon-miner",
    name: "Lumberloon + Miner",
    deckA: "loon-control",
    deckB: "miner-poison",
    winRate: 54.7,
    notes: "Freeze loon with a control partner that holds the opposite lane. Poison covers swarms Freeze cannot.",
  },
  {
    id: "mk-hog",
    name: "MK Bait + Hog",
    deckA: "mk-bait",
    deckB: "hog-cycle",
    winRate: 54.2,
    notes: "Mid-ladder stomper. One player soaks with MK, the other cycles Hog the moment a spell is spent.",
  },
  {
    id: "siege-bridge",
    name: "Mortar + Ram PEKKA",
    deckA: "mortar-bait",
    deckB: "ram-pekka",
    winRate: 53.9,
    notes: "Siege locks a tower while bridge spam threatens the other. Do not both drop buildings on one side.",
  },
  {
    id: "egiant-cycle",
    name: "E-Giant + Hog EQ",
    deckA: "egiant",
    deckB: "hog-miner",
    winRate: 53.3,
    notes: "Tornado value plus a building-breaking partner. The cycle deck must defend the first 60 seconds.",
  },
];

export const CARD_META: Record<string, CardMeta> = {
  skeletons: { key: "skeletons", usage: 18.4, winRate: 53.6, tier: "S+", trend: "flat" },
  "barbarian-barrel": { key: "barbarian-barrel", usage: 16.1, winRate: 53.2, tier: "S+", trend: "flat" },
  fireball: { key: "fireball", usage: 14.8, winRate: 52.9, tier: "S+", trend: "flat" },
  knight: { key: "knight", usage: 15.2, winRate: 53.1, tier: "S+", trend: "up" },
  "the-log": { key: "the-log", usage: 22.7, winRate: 53.4, tier: "S+", trend: "flat" },
  tesla: { key: "tesla", usage: 9.8, winRate: 53.8, tier: "S", trend: "up" },
  zap: { key: "zap", usage: 11.4, winRate: 51.9, tier: "S", trend: "down" },
  "electro-spirit": { key: "electro-spirit", usage: 8.2, winRate: 51.1, tier: "S", trend: "down" },
  goblins: { key: "goblins", usage: 7.6, winRate: 54.1, tier: "S", trend: "up" },
  "hog-rider": { key: "hog-rider", usage: 14.1, winRate: 54.0, tier: "S", trend: "flat" },
  balloon: { key: "balloon", usage: 6.4, winRate: 53.6, tier: "S", trend: "flat" },
  "royal-giant": { key: "royal-giant", usage: 4.2, winRate: 52.4, tier: "S", trend: "flat" },
  goblinstein: { key: "goblinstein", usage: 3.1, winRate: 53.9, tier: "S", trend: "up" },
  "ice-spirit": { key: "ice-spirit", usage: 13.5, winRate: 52.2, tier: "A", trend: "down" },
  bomber: { key: "bomber", usage: 4.8, winRate: 52.6, tier: "A", trend: "flat" },
  "dark-prince": { key: "dark-prince", usage: 3.9, winRate: 52.8, tier: "A", trend: "up" },
  "mega-minion": { key: "mega-minion", usage: 5.1, winRate: 52.1, tier: "A", trend: "flat" },
  valkyrie: { key: "valkyrie", usage: 9.4, winRate: 52.7, tier: "A", trend: "flat" },
  poison: { key: "poison", usage: 6.8, winRate: 53.3, tier: "A", trend: "up" },
  miner: { key: "miner", usage: 7.2, winRate: 53.1, tier: "A", trend: "up" },
  musketeer: { key: "musketeer", usage: 8.6, winRate: 53.4, tier: "A", trend: "flat" },
  cannon: { key: "cannon", usage: 10.2, winRate: 53.0, tier: "A", trend: "flat" },
  firecracker: { key: "firecracker", usage: 7.9, winRate: 50.4, tier: "A", trend: "down" },
  "royal-hogs": { key: "royal-hogs", usage: 6.1, winRate: 53.5, tier: "A", trend: "up" },
  "mega-knight": { key: "mega-knight", usage: 9.7, winRate: 52.3, tier: "A", trend: "up" },
  "goblin-barrel": { key: "goblin-barrel", usage: 11.8, winRate: 52.9, tier: "A", trend: "flat" },
  princess: { key: "princess", usage: 8.4, winRate: 53.0, tier: "A", trend: "flat" },
  "archer-queen": { key: "archer-queen", usage: 4.4, winRate: 53.7, tier: "A", trend: "flat" },
  "mighty-miner": { key: "mighty-miner", usage: 4.5, winRate: 53.2, tier: "A", trend: "flat" },
  "battle-ram": { key: "battle-ram", usage: 3.6, winRate: 54.1, tier: "A", trend: "up" },
  pekka: { key: "pekka", usage: 3.2, winRate: 53.4, tier: "A", trend: "up" },
  "royal-ghost": { key: "royal-ghost", usage: 5.5, winRate: 52.6, tier: "A", trend: "flat" },
  vines: { key: "vines", usage: 3.8, winRate: 52.9, tier: "A", trend: "up" },
  earthquake: { key: "earthquake", usage: 7.1, winRate: 53.6, tier: "A", trend: "up" },
  "royal-delivery": { key: "royal-delivery", usage: 6.6, winRate: 53.1, tier: "A", trend: "flat" },
  mortar: { key: "mortar", usage: 2.1, winRate: 54.4, tier: "A", trend: "up" },
  "boss-bandit": { key: "boss-bandit", usage: 3.4, winRate: 52.2, tier: "A", trend: "flat" },
  "ice-wizard": { key: "ice-wizard", usage: 3.0, winRate: 56.3, tier: "S", trend: "up" },
  tombstone: { key: "tombstone", usage: 2.8, winRate: 52.4, tier: "B", trend: "up" },
  ronin: { key: "ronin", usage: 1.2, winRate: 54.8, tier: "B", trend: "up" },
  "minion-giant": { key: "minion-giant", usage: 1.8, winRate: 51.6, tier: "B", trend: "up" },
  "spirit-empress": { key: "spirit-empress", usage: 1.9, winRate: 52.4, tier: "B", trend: "flat" },
  void: { key: "void", usage: 1.1, winRate: 49.8, tier: "C", trend: "down" },
  "rune-giant": { key: "rune-giant", usage: 0.6, winRate: 48.4, tier: "D", trend: "down" },
};

export function cardMeta(key: string): CardMeta {
  return (
    CARD_META[key] ?? {
      key,
      usage: 1.2,
      winRate: 50.4,
      tier: "C",
      trend: "flat",
    }
  );
}

export function deckById(id: string): MetaDeck | undefined {
  return META_DECKS.find((d) => d.id === id);
}
