/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as ClanRouteImport } from './routes/clan'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as UpgradesRouteImport } from './routes/upgrades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ClanRoute = ClanRouteImport.update({
  id: '/clan',
  path: '/clan',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradesRoute = UpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/clan': typeof ClanRoute
  '/coach': typeof CoachRoute
  '/meta': typeof MetaRoute
  '/ops': typeof OpsRoute
  '/player': typeof PlayerRoute
  '/upgrades': typeof UpgradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/clan': typeof ClanRoute
  '/coach': typeof CoachRoute
  '/meta': typeof MetaRoute
  '/ops': typeof OpsRoute
  '/player': typeof PlayerRoute
  '/upgrades': typeof UpgradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/clan': typeof ClanRoute
  '/coach': typeof CoachRoute
  '/meta': typeof MetaRoute
  '/ops': typeof OpsRoute
  '/player': typeof PlayerRoute
  '/upgrades': typeof UpgradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/clan'
    | '/coach'
    | '/meta'
    | '/ops'
    | '/player'
    | '/upgrades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/clan'
    | '/coach'
    | '/meta'
    | '/ops'
    | '/player'
    | '/upgrades'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/clan'
    | '/coach'
    | '/meta'
    | '/ops'
    | '/player'
    | '/upgrades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  ClanRoute: typeof ClanRoute
  CoachRoute: typeof CoachRoute
  MetaRoute: typeof MetaRoute
  OpsRoute: typeof OpsRoute
  PlayerRoute: typeof PlayerRoute
  UpgradesRoute: typeof UpgradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clan': {
      id: '/clan'
      path: '/clan'
      fullPath: '/clan'
      preLoaderRoute: typeof ClanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrades': {
      id: '/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof UpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  ClanRoute: ClanRoute,
  CoachRoute: CoachRoute,
  MetaRoute: MetaRoute,
  OpsRoute: OpsRoute,
  PlayerRoute: PlayerRoute,
  UpgradesRoute: UpgradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
